kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: oc-quarkus-s2i
spec:
  workspaces:
    - name: build-workspace
      description: Build workspace.
  params:
    - name: APP_NAME
      type: string
  steps:
    - name: run-commands
      image: quay.io/openshift/origin-cli:latest
      workingDir: $(workspaces.build-workspace.path)
      script: |
        #!/usr/bin/env bash
        echo "List current dir contents:"
        ls -la .
        echo "List target contents:"
        ls -l $(workspaces.build-workspace.path)/target
        JAR="$(ls $(workspaces.build-workspace.path)/target/*-runner.jar)"
        echo "Building image with ${JAR}"
        oc start-build $(inputs.params.APP_NAME)-s2i-build --from-file=$JAR -n cicd --follow
