kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
  name: quarkus-maven-build
spec:
  workspaces:
    - name: build-workspace
    - name: local-maven-repo
  params:
    - name: git-repo-revision
      type: string
      default: master
    - name: git-repo-url
      type: string
  tasks:
    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: build-workspace
      params:
        - name: url
          value: "$(params.git-repo-url)"
        - name: revision
          value: "$(params.git-repo-revision)"
        - name: deleteExisting
          value: "true"
    - name: build
      taskRef:
        kind: Task
        name: maven
      runAfter:
        - clone 
      params:
        - name: GOALS
          value: ["clean", "package"]
      workspaces:
        - name: local-maven-repo
          workspace: local-maven-repo
        - name: build-workspace
          workspace: build-workspace
    - name: begin-s2i
      taskRef:
        kind: Task
        name: oc-quarkus-s2i
      runAfter:
        - build 
      params:
        - name: APP_NAME
          value: quarkus
      workspaces:
        - name: build-workspace
          workspace: build-workspace
    - name: deploy-dev
      taskRef:
        kind: Task
        name: openshift-client
      runAfter:
        - begin-s2i 
      params:
        - name: COMMANDS
          value: |
              oc rollout latest dc/quarkus -n quarkus-dev
              oc rollout status dc/quarkus -n quarkus-dev
    - name: deploy-uat
      taskRef:
        kind: Task
        name: openshift-client
      runAfter:
        - deploy-dev
      params:
        - name: COMMANDS
          value: |
              oc rollout latest dc/quarkus -n quarkus-uat
              oc rollout status dc/quarkus -n quarkus-uat
