apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: quarkus-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
      - name: quarkus-binding
      template:
        name: quarkus-template